SiCandiWeb2017/App_Data/Controllers/CandidataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using SiCandi2017.Controlador;



namespace SisCandidatasWeb_2017.Controllers
{
    public class CandidataController : Controller
    {
        // GET: Candidata
        public ActionResult Index(string word = "", string m = "")
        {
            ViewBag.DatosC = ManejoCandidata.Buscar(word,true, m);
            ViewBag.DatosM = ManejoMunicipio.getAll(true);
            ViewBag.word = word;
            return View();
        }

        public ActionResult Like(int pkCandidata)
        {
            ManejoCandidata.Like(pkCandidata);
            return RedirectToAction("");
        }
    }
}

SiCandiWeb2017/App_Data/Views/Candidata/Index.cshtml
@{
     ViewBag.Title = "Index";
    List<SiCandi_Library.Modelo.Candidata> DatosC = ViewBag.DatosC;
    List<SiCandi_Library.Modelo.Municipio> DatosM = ViewBag.DatosM;
    string word = ViewBag.word;
}

<br />

<div class="">
    <div class="col s12">
        @using (Html.BeginForm("Index","Candidata",FormMethod.Get))
        {
            <div class="input-field col s4">
                <input id="name" type="text" name="word" placeholder="Buscar por Nombre" value="@word"/><br />
            </div>
            <div class="col">
                <select id="municipios" name="m">c
                    <option value="" disabled selected>Elija un municipio</option>
                    @foreach (SiCandi_Library.Modelo.Municipio item in DatosM)
                    {
                        <option value="@item.sNombre">@item.sNombre</option>
                    }
                </select>
            </div>
            <div class="col ">
                <button type="submit" class="white-text waves-effect waves-light btn"><i class="material-icons">search</i></button>
            </div>
        }
    </div>
</div>

<div class="row">
    <div class="col s12">
        @foreach (SiCandi_Library.Modelo.Candidata item in DatosC) {
            <div class="col s4">
                <div class="card hoverable">
                    <div class="card-image">
                        <img class="responsive-img"
                             src="data:image/png;base64,@item.sFotografiaRostro" alt="@item.sNombreCompleto">
                     
                    </div>
                    <div class="card-content">
                        <p><b>Nombre: </b>@item.sNombreCompleto</p>
                        <p><b>Estudios: </b>@item.sNivelEstudios</p>
                        <p><b>Descripción: </b>@item.sDescripcion</p>
                        <p><b>Fecha de Nacimiento: </b>@item.dtFechaNacimiento</p>
                    </div>
                    <div class="card-action">
                        @using (Html.BeginForm("Like", "Candidata", FormMethod.Post))
                        {
                            <input type="hidden" name="pkCandidata" value="@item.pkCandidata" />
                            <div class="center-align">
                                <button type="submit" class="white-text waves-effect waves-light btn">Me Gusta</button>
                                <h5>@item.iLike Me Gustas</h5>
                            </div>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

SiCandiWeb2017/App_Data/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Candidatas a Reina 2017</title>
    <link href="~/Content/materialize.min.css" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body class="grey lighten-4">
    <div class="navbar-brand">
        <nav class="teal">
            <div class="nav-wrapper">
                <div class="container">
                @Html.ActionLink("Candidatas a Reina 2017", "Index", "Candidata", new { area = "" }, new { @class = "brand-logo" })
                </div>
            </div>
        </nav>
    </div>

    <div class="container">
        @RenderBody()
    </div>
    <footer class="page-footer teal">
        <div class="footer-copyright">
            <div class="container">
                &copy; @DateTime.Now.Year - Desarollo de Aplicaciones III.
            </div>
        </div>
    </footer>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/materialize.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('select').material_select();
        });
    </script>
</body>
</html>